### PR TITLE
Add service provider and facade tests.

### PR DESCRIPTION
**Pull request by vinkla**

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Can you apply the patch file as per https://styleci.io/commits/e88118d7b85b05c0363a1dcb2cfcd76198da1da6 then we'll merge :(

**Comment by vinkla** [comment]
Same as in https://github.com/notifymehq/laravel5/pull/4.

**Comment by GrahamCampbell** [comment]
We need the namespace to be `NotifyMeHQ\Tests\Laravel4`, then we're sorted.

**Comment by vinkla** [comment]
Done.

**Comment by vinkla** [comment]
Thank you!

**Comment by jbrooksuk** [comment]
No, thank you! :)

**Pull request merged**
